#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $LEGEND_REPO == "THEPANDABOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZXBhbjgwOC9USEVQQU5EQVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $THEPAN_REPO == "THEPANDABOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZXBhbjgwOC9USEVQQU5EQVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $THEPAN_REPO =~ $regex ]]
    then
        if [[ $THEPAN_REPO_BRANCH ]]
        then
            echo "${LEGEND_REPO}/archive/${LEGEND_REPO_BRANCH}.zip"
        else
            echo "${LEGEND_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZXBhbjgwOC9USEVQQU5EQVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="THEPANDABOT.zip"
    echo "  ⚜Baixando Thepanda V3.0...❤"
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    LEGENDPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  LegendBot V3.0 Cleaning.."
    rm -rf "$zippath"
    sleep 5
    cd $LEGENDPATH
    echo "    • Starting Lêɠêɳ̃dẞøt 3.0•    "
    echo "
    LEGENDBOT
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
